import { Project, AnalysisResult, SpecialistModel, BenchmarkDataset, ReportItem } from '../types';

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-urban-01',
    name: 'Bengaluru Peri-Urban Expansion',
    description: 'Bi-temporal satellite monitoring of infrastructure expansion, new industrial zones, and land use conversion along NH-44.',
    theme: 'Urban',
    regionName: 'Bengaluru North / Devanahalli Corridor, India',
    centerCoordinates: [13.125, 77.625],
    zoomLevel: 13,
    defaultMode: 'BITEMPORAL_CHANGE',
    images: [
      {
        id: 'img-beng-t1',
        name: 'Sentinel2_MSI_20240315_T1.tif',
        url: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=200&q=80',
        modality: 'optical',
        temporalType: 't1',
        uploadedAt: '2026-03-01T10:15:00Z',
        metadata: {
          format: 'GeoTIFF / COG (Cloud Optimized)',
          crs: 'EPSG:32643 (WGS 84 / UTM Zone 43N)',
          crsStatus: 'valid',
          dimensions: { width: 4096, height: 4096 },
          resolution: '10.0m GSD',
          pixelSizeMeters: 10.0,
          bands: ['B02-Blue', 'B03-Green', 'B04-Red', 'B08-NIR'],
          sensor: 'Sentinel-2 MSI Level-2A',
          acquisitionDate: '2024-03-15T05:42:10Z',
          bbox: [77.58, 13.08, 77.67, 13.17],
          center: [13.125, 77.625],
          fileSize: '48.6 MB',
          radiometricBits: 12,
          cloudCoverPercentage: 0.8,
        },
      },
      {
        id: 'img-beng-t2',
        name: 'Sentinel2_MSI_20260228_T2.tif',
        url: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=200&q=80',
        modality: 'optical',
        temporalType: 't2',
        uploadedAt: '2026-03-01T10:18:00Z',
        metadata: {
          format: 'GeoTIFF / COG (Cloud Optimized)',
          crs: 'EPSG:32643 (WGS 84 / UTM Zone 43N)',
          crsStatus: 'valid',
          dimensions: { width: 4096, height: 4096 },
          resolution: '10.0m GSD',
          pixelSizeMeters: 10.0,
          bands: ['B02-Blue', 'B03-Green', 'B04-Red', 'B08-NIR'],
          sensor: 'Sentinel-2 MSI Level-2A',
          acquisitionDate: '2026-02-28T05:41:48Z',
          bbox: [77.58, 13.08, 77.67, 13.17],
          center: [13.125, 77.625],
          fileSize: '49.1 MB',
          radiometricBits: 12,
          cloudCoverPercentage: 1.2,
        },
      },
    ],
    validation: {
      status: 'READY',
      summary: 'Bi-temporal imagery validated. Spatial extents match, CRS is consistent (EPSG:32643), GSD is identical (10m), and temporal delta is 715 days.',
      checks: [
        { id: 'v-1', category: 'file', name: 'File Format & Integrity', status: 'passed', detail: 'GeoTIFF Level-2A validated; No compression artifacts or missing tiles.' },
        { id: 'v-2', category: 'georeferencing', name: 'CRS Verification', status: 'passed', detail: 'Both images use EPSG:32643 (UTM Zone 43N).' },
        { id: 'v-3', category: 'georeferencing', name: 'Spatial Extent Overlap', status: 'passed', detail: 'Intersection coverage: 99.8% geometric congruence.' },
        { id: 'v-4', category: 'sensor', name: 'GSD & Band Compatibility', status: 'passed', detail: 'Identical 10m GSD across VNIR bands (B2, B3, B4, B8).' },
        { id: 'v-5', category: 'compatibility', name: 'Temporal Co-registration', status: 'passed', detail: 'Relative geo-referencing RMSE is 0.22 pixels. Ready for change detection.' },
      ],
      timestamp: '2026-03-01T10:19:00Z',
    },
    recentAnalyses: [],
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'proj-brahmaputra-02',
    name: 'Brahmaputra Basin Flood Inundation',
    description: 'Joint Optical and Synthetic Aperture Radar (SAR) cross-modal analysis for all-weather flood boundary delineation in cloud-covered periods.',
    theme: 'Disaster',
    regionName: 'Kaziranga / Nagaon Reach, Assam, India',
    centerCoordinates: [26.65, 93.18],
    zoomLevel: 12,
    defaultMode: 'OPTICAL_SAR_FUSION',
    images: [
      {
        id: 'img-assam-opt',
        name: 'Sentinel2_Optical_CloudCovered.tif',
        url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=200&q=80',
        modality: 'optical',
        temporalType: 'single',
        uploadedAt: '2026-02-20T08:00:00Z',
        metadata: {
          format: 'GeoTIFF',
          crs: 'EPSG:32646 (WGS 84 / UTM Zone 46N)',
          crsStatus: 'valid',
          dimensions: { width: 3800, height: 3800 },
          resolution: '10.0m GSD',
          pixelSizeMeters: 10.0,
          bands: ['Red', 'Green', 'Blue', 'NIR', 'SWIR'],
          sensor: 'Sentinel-2 MSI',
          acquisitionDate: '2026-02-18T04:12:00Z',
          bbox: [93.10, 26.58, 93.26, 26.72],
          center: [26.65, 93.18],
          fileSize: '52.4 MB',
          radiometricBits: 12,
          cloudCoverPercentage: 38.4,
        },
      },
      {
        id: 'img-assam-sar',
        name: 'Sentinel1_SAR_GRD_IW_VV_VH.tif',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=200&q=80',
        modality: 'sar',
        temporalType: 'single',
        uploadedAt: '2026-02-20T08:05:00Z',
        metadata: {
          format: 'GeoTIFF / SAR GRD',
          crs: 'EPSG:32646 (WGS 84 / UTM Zone 46N)',
          crsStatus: 'valid',
          dimensions: { width: 3800, height: 3800 },
          resolution: '10.0m GSD (terrain corrected)',
          pixelSizeMeters: 10.0,
          bands: ['Gamma0_VV', 'Gamma0_VH', 'Ratio_VV_VH'],
          sensor: 'Sentinel-1 C-SAR IW Mode',
          acquisitionDate: '2026-02-18T12:35:00Z',
          bbox: [93.10, 26.58, 93.26, 26.72],
          center: [26.65, 93.18],
          fileSize: '61.0 MB',
          radiometricBits: 16,
          polarization: 'VV + VH dual-pol',
          orbitDirection: 'Descending',
        },
      },
    ],
    validation: {
      status: 'READY',
      summary: 'Cross-modal Optical-SAR pair validated. Same geographic footprint in UTM Zone 46N. Optical cloud occlusion (38.4%) will be supplemented by radar backscatter.',
      checks: [
        { id: 'v-b1', category: 'file', name: 'Format Compatibility', status: 'passed', detail: 'GeoTIFF multispectral & SAR GRD detected.' },
        { id: 'v-b2', category: 'georeferencing', name: 'Spatial Co-registration', status: 'passed', detail: 'Sub-pixel co-registration verified (RMSE 0.18 px).' },
        { id: 'v-b3', category: 'sensor', name: 'Sensor Complementarity', status: 'passed', detail: 'Optical VNIR/SWIR combined with C-band active microwave.' },
        { id: 'v-b4', category: 'compatibility', name: 'Temporal Proximity', status: 'passed', detail: 'Both observations acquired within 8.4 hours on same date.' },
      ],
      timestamp: '2026-02-20T08:06:00Z',
    },
    recentAnalyses: [],
    createdAt: '2026-02-20T07:45:00Z',
  },
  {
    id: 'proj-punjab-agri-03',
    name: 'Punjab Crop Phenology & Water Bodies',
    description: 'High-resolution single-image agricultural land use classification, canal mapping, and crop vigor assessment.',
    theme: 'Agriculture',
    regionName: 'Bhatinda / Malwa Agricultural Belt, Punjab, India',
    centerCoordinates: [30.21, 74.95],
    zoomLevel: 13,
    defaultMode: 'SINGLE_VQA',
    images: [
      {
        id: 'img-punjab-single',
        name: 'Resourcesat_LISS4_Punjab_Crop.tif',
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=200&q=80',
        modality: 'optical',
        temporalType: 'single',
        uploadedAt: '2026-02-15T09:20:00Z',
        metadata: {
          format: 'GeoTIFF',
          crs: 'EPSG:32643 (WGS 84 / UTM Zone 43N)',
          crsStatus: 'valid',
          dimensions: { width: 5000, height: 5000 },
          resolution: '5.8m GSD',
          pixelSizeMeters: 5.8,
          bands: ['Green (B2)', 'Red (B3)', 'NIR (B4)'],
          sensor: 'Resourcesat-2A LISS-IV',
          acquisitionDate: '2026-01-22T05:15:30Z',
          bbox: [74.90, 30.16, 75.00, 30.26],
          center: [30.21, 74.95],
          fileSize: '36.8 MB',
          radiometricBits: 10,
          cloudCoverPercentage: 0.0,
        },
      },
    ],
    validation: {
      status: 'READY',
      summary: 'Single-image remote-sensing asset validated. High quality 5.8m GSD with zero cloud cover.',
      checks: [
        { id: 'v-p1', category: 'file', name: 'File Integrity', status: 'passed', detail: 'Uncorrupted GeoTIFF structure.' },
        { id: 'v-p2', category: 'georeferencing', name: 'Coordinate Georeferencing', status: 'passed', detail: 'Valid UTM Zone 43N coordinate transform.' },
        { id: 'v-p3', category: 'sensor', name: 'Multispectral Radiometry', status: 'passed', detail: 'Calibrated top-of-atmosphere reflectance in 3 bands.' },
      ],
      timestamp: '2026-02-15T09:21:00Z',
    },
    recentAnalyses: [],
    createdAt: '2026-02-15T09:00:00Z',
  },
];

export const DEMO_SCENARIO_RESULTS: Record<string, AnalysisResult> = {
  // Scenario 1: Single Image VQA
  scenario_single_vqa: {
    id: 'res-single-vqa-01',
    projectId: 'proj-punjab-agri-03',
    query: 'What major land-cover types are visible?',
    analysisMode: 'SINGLE_VQA',
    modeLabel: 'Single-Image Visual Question Answering',
    answer: 'The satellite scene is predominantly characterized by irrigated agricultural cropland (68.4%), interspersed with an active dendritic irrigation canal and wetland reservoir in the southeastern zone (14.2%). Clustered rural built-up settlements and farm homesteads occupy 9.8%, with the remaining 7.6% consisting of natural roadside shelterbelt trees and fallow plots.',
    evidenceSummary: 'Spectral signature classification derived from NIR/Red vegetation indices and water absorption bands.',
    confidence: {
      score: 0.91,
      tier: 'HIGH',
      explanation: 'High confidence based on distinct spectral separation in LISS-IV VNIR bands and high consensus across RS-VQA specialist model heads.',
      basis: 'RSVQA-fine-tuned vision-language backbone with calibrated land-cover entropy < 0.12.',
    },
    evidenceItems: [
      {
        id: 'ev-vqa-1',
        title: 'Agricultural Cropland Parcels',
        type: 'segmentation_mask',
        description: 'Dense active photosynthetic canopy highlighted across the central plain.',
        layerId: 'layer-crops',
        centerCoords: [30.21, 74.95],
        targetZoom: 13,
        activeByDefault: true,
        colorCode: '#22C55E',
      },
      {
        id: 'ev-vqa-2',
        title: 'Southeastern Water Reservoir',
        type: 'grounding_box',
        description: 'Perennial irrigation reservoir with high absorption in NIR band.',
        layerId: 'layer-water',
        centerCoords: [30.185, 74.975],
        targetZoom: 14,
        activeByDefault: true,
        colorCode: '#22D3EE',
      },
    ],
    executionTrace: {
      id: 'tr-vqa-01',
      query: 'What major land-cover types are visible?',
      detectedMode: 'SINGLE_VQA',
      modeLabel: 'Single-Image Visual Question Answering',
      confidenceScore: 0.91,
      totalDurationMs: 840,
      specialistModelsUsed: ['RS-VQA Specialist Model v2.1', 'Multispectral Feature Extractor'],
      completedAt: '2026-03-02T11:00:15Z',
      steps: [
        {
          id: 'step-1',
          phase: 'Input Validation',
          title: 'Input Verification & CRS Inspection',
          description: 'Verified 1 GeoTIFF image (Resourcesat-2A LISS-IV). Extracted EPSG:32643 coordinate bounds.',
          status: 'completed',
          latencyMs: 85,
          timestamp: '2026-03-02T11:00:14.200Z',
          inputContract: { imageCount: 1, format: 'GeoTIFF', bands: 3 },
          outputContract: { valid: true, crs: 'EPSG:32643', gsdMeters: 5.8 },
        },
        {
          id: 'step-2',
          phase: 'Query Understanding',
          title: 'Semantic Query Parsing & Intent Extraction',
          description: 'Identified intent: Comprehensive land-cover distribution query. Target: Entire spatial extent.',
          status: 'completed',
          latencyMs: 110,
          timestamp: '2026-03-02T11:00:14.285Z',
          inputContract: { query: 'What major land-cover types are visible?' },
          outputContract: { intent: 'land_cover_summary', granularity: 'scene_level' },
        },
        {
          id: 'step-3',
          phase: 'Specialist Selection',
          title: 'Agentic Model Routing',
          description: 'Controller selected RS-VQA Specialist Model v2.1 (Domain-adapted on RSVQA + VRSBench).',
          status: 'completed',
          latencyMs: 45,
          timestamp: '2026-03-02T11:00:14.395Z',
          toolUsed: 'Agentic Controller Router',
        },
        {
          id: 'step-4',
          phase: 'Remote-Sensing Inference',
          title: 'Vision-Language Feature Extraction & Spatial Attention',
          description: 'Computed cross-modal cross-attention between textual question tokens and spatial feature maps.',
          status: 'completed',
          latencyMs: 420,
          timestamp: '2026-03-02T11:00:14.440Z',
          toolUsed: 'RS-VQA Specialist Model v2.1',
        },
        {
          id: 'step-5',
          phase: 'Result Integration',
          title: 'Evidence Verification & Calibrated Answer Synthesis',
          description: 'Synthesized natural-language response with grounded percentage breakdowns and spatial evidence.',
          status: 'completed',
          latencyMs: 180,
          timestamp: '2026-03-02T11:00:14.860Z',
        },
      ],
    },
    sourceImages: {},
    createdAt: '2026-03-02T11:00:15Z',
  },

  // Scenario 2: Region Grounding
  scenario_grounding: {
    id: 'res-grounding-02',
    projectId: 'proj-punjab-agri-03',
    query: 'Highlight the water body.',
    analysisMode: 'SINGLE_GROUNDING',
    modeLabel: 'Visual Region Grounding & Spatial Localization',
    answer: 'The primary surface water body was localized in the southeastern quadrant of the study area (Coordinates: 30.185°N, 74.975°E). It corresponds to a perennial municipal irrigation reservoir covering approximately 42.6 hectares, showing near-zero spectral reflectance in NIR (NDWI > 0.62).',
    evidenceSummary: 'Precise bounding box [74.962, 30.174, 74.988, 30.196] and segmentation mask overlay.',
    confidence: {
      score: 0.94,
      tier: 'HIGH',
      explanation: 'Extremely high confidence due to unambiguous negative NIR values and sharp contrast with surrounding vegetation.',
      basis: 'RS-Grounding Specialist model IoU consensus with automated NDWI thresholding.',
    },
    groundingRegions: [
      {
        id: 'gr-water-01',
        label: 'Irrigation Reservoir (NDWI: 0.64)',
        confidence: 0.94,
        bbox: [74.962, 30.174, 74.988, 30.196],
        color: '#22D3EE',
        areaHa: 42.6,
      },
    ],
    evidenceItems: [
      {
        id: 'ev-gr-1',
        title: 'Water Reservoir Bounding Extent',
        type: 'grounding_box',
        description: 'Exact spatial bounding box coordinates enclosing the detected water body.',
        layerId: 'layer-grounding-box',
        centerCoords: [30.185, 74.975],
        targetZoom: 15,
        activeByDefault: true,
        colorCode: '#22D3EE',
      },
      {
        id: 'ev-gr-2',
        title: 'Normalized Difference Water Index (NDWI) Mask',
        type: 'segmentation_mask',
        description: 'Pixel-level segmentation mask differentiating open water from muddy embankment.',
        layerId: 'layer-ndwi-mask',
        centerCoords: [30.185, 74.975],
        targetZoom: 15,
        activeByDefault: true,
        colorCode: '#14B8A6',
      },
    ],
    executionTrace: {
      id: 'tr-gr-02',
      query: 'Highlight the water body.',
      detectedMode: 'SINGLE_GROUNDING',
      modeLabel: 'Visual Region Grounding',
      confidenceScore: 0.94,
      totalDurationMs: 690,
      specialistModelsUsed: ['RS-Grounding Specialist v2.0', 'NDWI Spatial Validator'],
      completedAt: '2026-03-02T11:15:20Z',
      steps: [
        {
          id: 'step-g1',
          phase: 'Input Validation',
          title: 'Input Inspection',
          description: 'Single image mode confirmed. Bounding coordinate bounds [74.90, 30.16, 75.00, 30.26].',
          status: 'completed',
          latencyMs: 70,
          timestamp: '2026-03-02T11:15:19.300Z',
        },
        {
          id: 'step-g2',
          phase: 'Query Understanding',
          title: 'Target Entity Identification',
          description: 'Target query entity parsed: "water body". Task type: Spatial Grounding / Box Localization.',
          status: 'completed',
          latencyMs: 95,
          timestamp: '2026-03-02T11:15:19.370Z',
        },
        {
          id: 'step-g3',
          phase: 'Specialist Selection',
          title: 'RS-Grounding Specialist Engaged',
          description: 'Dispatched query and image tensor to Text-Guided Geospatial Bounding Box model.',
          status: 'completed',
          latencyMs: 40,
          timestamp: '2026-03-02T11:15:19.465Z',
          toolUsed: 'RS-Grounding Specialist v2.0',
        },
        {
          id: 'step-g4',
          phase: 'Remote-Sensing Inference',
          title: 'Bounding Box Regression & Mask Generation',
          description: 'Regressed spatial coordinates [74.962, 30.174, 74.988, 30.196] with IoU overlap 0.91.',
          status: 'completed',
          latencyMs: 340,
          timestamp: '2026-03-02T11:15:19.505Z',
          toolUsed: 'RS-Grounding Specialist v2.0',
        },
        {
          id: 'step-g5',
          phase: 'Result Integration',
          title: 'Evidence Ready & Viewport Animation Trigger',
          description: 'Generated interactive evidence overlay. Centered viewport on [30.185, 74.975].',
          status: 'completed',
          latencyMs: 145,
          timestamp: '2026-03-02T11:15:19.845Z',
        },
      ],
    },
    sourceImages: {},
    createdAt: '2026-03-02T11:15:20Z',
  },

  // Scenario 3: Bi-Temporal Change Analysis
  scenario_bitemporal_change: {
    id: 'res-bitemp-03',
    projectId: 'proj-urban-01',
    query: 'What changed between these two dates?',
    analysisMode: 'BITEMPORAL_CHANGE',
    modeLabel: 'Bi-Temporal Change Detection & Description',
    answer: 'Extensive peri-urban expansion and industrial infrastructure development occurred between March 2024 (T1) and February 2026 (T2). The most pronounced change is clustered along the northern arterial corridor (NH-44 bypass), where 3.42 km² of previously barren and agricultural parcels were converted into high-reflectance commercial logistics warehouses and paved transport spurs.',
    evidenceSummary: 'Binary change heatmap, 14 detected cluster polygons, and multi-spectral difference indices.',
    confidence: {
      score: 0.89,
      tier: 'HIGH',
      explanation: 'High confidence based on temporal spectral differencing agreement between Siamese ViT change model and bi-temporal NDBI building index shifts.',
      basis: 'Siamese RS-Transformer change detection head with cross-date feature correlation > 0.86.',
    },
    statistics: {
      changedAreaKm2: 3.42,
      percentageChange: 18.4,
      baselineBuiltUpKm2: 18.58,
      currentBuiltUpKm2: 22.00,
      detectedRegionsCount: 14,
      confidenceMetric: 'P90 Siamese Consensus: 0.89',
      calculationMethod: 'Pixel-level radiometric normalization followed by thresholded change vector analysis (CVA)',
    },
    evidenceItems: [
      {
        id: 'ev-bt-1',
        title: 'Bi-Temporal Change Mask (Red Overlay)',
        type: 'change_map',
        description: 'Areas where land cover transformed from non-built to impermeable built structure.',
        layerId: 'layer-change-mask',
        centerCoords: [13.142, 77.632],
        targetZoom: 14,
        activeByDefault: true,
        colorCode: '#EF4444',
      },
      {
        id: 'ev-bt-2',
        title: 'Northern Commercial Warehouse Cluster',
        type: 'segmentation_mask',
        description: 'Largest single cluster of new construction spanning 1.18 km².',
        layerId: 'layer-cluster-north',
        centerCoords: [13.155, 77.638],
        targetZoom: 15,
        activeByDefault: true,
        colorCode: '#F59E0B',
      },
      {
        id: 'ev-bt-3',
        title: 'T1 vs T2 Swipe Comparison',
        type: 'optical_sar_overlay',
        description: 'Interactive split-view allowing instant visual confirmation of building footprints.',
        layerId: 'layer-swipe',
        centerCoords: [13.125, 77.625],
        targetZoom: 13,
        activeByDefault: false,
        colorCode: '#22D3EE',
      },
    ],
    executionTrace: {
      id: 'tr-bt-03',
      query: 'What changed between these two dates?',
      detectedMode: 'BITEMPORAL_CHANGE',
      modeLabel: 'Bi-Temporal Change Detection',
      confidenceScore: 0.89,
      totalDurationMs: 1120,
      specialistModelsUsed: ['Co-registration Validator', 'Siamese Change Detection Net v3.2', 'Change-Captioning Specialist'],
      completedAt: '2026-03-02T12:04:30Z',
      steps: [
        {
          id: 'step-b1',
          phase: 'Input Validation',
          title: 'Bi-Temporal Pair Validation & CRS Check',
          description: 'Checked 2 GeoTIFFs (T1: 2024-03-15 vs T2: 2026-02-28). Verified matching EPSG:32643 and 10m GSD.',
          status: 'completed',
          latencyMs: 95,
          timestamp: '2026-03-02T12:04:28.880Z',
          inputContract: { t1Date: '2024-03-15', t2Date: '2026-02-28', sensor: 'Sentinel-2' },
          outputContract: { crsMatch: true, gsdMatch: true, status: 'READY' },
        },
        {
          id: 'step-b2',
          phase: 'Query Understanding',
          title: 'Temporal Delta Intent Extraction',
          description: 'Identified question as open-ended bi-temporal change detection and descriptive summarization.',
          status: 'completed',
          latencyMs: 105,
          timestamp: '2026-03-02T12:04:28.975Z',
        },
        {
          id: 'step-b3',
          phase: 'Specialist Selection',
          title: 'Multi-Model Tool Orchestration',
          description: 'Agent selected: 1) Co-registration tool, 2) Siamese Change Detection Net v3.2, 3) Change-Captioning Specialist.',
          status: 'completed',
          latencyMs: 60,
          timestamp: '2026-03-02T12:04:29.080Z',
          toolUsed: 'SatQuery Agent Controller',
        },
        {
          id: 'step-b4',
          phase: 'Remote-Sensing Inference',
          title: 'Siamese Feature Differencing & Change Map Generation',
          description: 'Extracted deep bi-temporal feature pyramids. Performed temporal cross-attention and classified change pixels.',
          status: 'completed',
          latencyMs: 580,
          timestamp: '2026-03-02T12:04:29.140Z',
          toolUsed: 'Siamese Change Detection Net v3.2',
        },
        {
          id: 'step-b5',
          phase: 'Result Integration',
          title: 'Geospatial Statistics Calculation & Natural Language Synthesis',
          description: 'Integrated 3.42 km² (+18.4%) quantitative metrics with vector change polygons and calibrated narrative.',
          status: 'completed',
          latencyMs: 280,
          timestamp: '2026-03-02T12:04:29.720Z',
        },
      ],
    },
    sourceImages: {},
    createdAt: '2026-03-02T12:04:30Z',
  },

  // Scenario 4: Change-Based VQA
  scenario_bitemporal_vqa: {
    id: 'res-changevqa-04',
    projectId: 'proj-urban-01',
    query: 'Has the built-up area increased?',
    analysisMode: 'BITEMPORAL_VQA',
    modeLabel: 'Change-Based Visual Question Answering (Change-VQA)',
    answer: 'YES. The built-up area increased significantly over the 2-year observation window. A net gain of +3.42 km² (+18.4% expansion) was detected, expanding total built-up surface from 18.58 km² to 22.00 km², with the heaviest growth occurring in the northern logistics and manufacturing sector.',
    evidenceSummary: 'Direct affirmative verification with spatial mask showing 14 newly built clusters.',
    confidence: {
      score: 0.92,
      tier: 'HIGH',
      explanation: 'High confidence based on unequivocal affirmative signals across both Normalized Difference Built-up Index (NDBI) and Siamese VQA decision heads.',
      basis: 'CDVQA-adapted temporal reasoning network with softmax certainty score of 0.924.',
    },
    statistics: {
      changedAreaKm2: 3.42,
      percentageChange: 18.4,
      baselineBuiltUpKm2: 18.58,
      currentBuiltUpKm2: 22.00,
      detectedRegionsCount: 14,
      confidenceMetric: 'Certainty Index: 0.92',
      calculationMethod: 'Change-VQA spatial classification verified against NDBI delta threshold (+0.18)',
    },
    evidenceItems: [
      {
        id: 'ev-cvqa-1',
        title: 'Affirmative Evidence: Changed Built-Up Footprint',
        type: 'change_map',
        description: 'Grounded spatial regions proving built-up surface expansion.',
        layerId: 'layer-built-up-evidence',
        centerCoords: [13.142, 77.632],
        targetZoom: 14,
        activeByDefault: true,
        colorCode: '#22C55E',
      },
    ],
    executionTrace: {
      id: 'tr-cvqa-04',
      query: 'Has the built-up area increased?',
      detectedMode: 'BITEMPORAL_VQA',
      modeLabel: 'Change-Based VQA',
      confidenceScore: 0.92,
      totalDurationMs: 910,
      specialistModelsUsed: ['Change-VQA Specialist Model v1.8', 'Spatial Change Validator'],
      completedAt: '2026-03-02T12:10:00Z',
      steps: [
        {
          id: 'step-c1',
          phase: 'Input Validation',
          title: 'Bi-Temporal Co-Registration Confirmation',
          description: 'Re-used validated bi-temporal pairs T1 & T2 with RMSE 0.22 pixels.',
          status: 'completed',
          latencyMs: 65,
          timestamp: '2026-03-02T12:09:59.090Z',
        },
        {
          id: 'step-c2',
          phase: 'Query Understanding',
          title: 'Polarity Query Classification',
          description: 'Identified question format as Boolean/Verification: [Target: Built-up, Direction: Increase].',
          status: 'completed',
          latencyMs: 90,
          timestamp: '2026-03-02T12:09:59.155Z',
        },
        {
          id: 'step-c3',
          phase: 'Specialist Selection',
          title: 'Change-VQA Specialist Selected',
          description: 'Dispatched to Change-VQA Specialist Model v1.8 (CDVQA benchmark baseline).',
          status: 'completed',
          latencyMs: 45,
          timestamp: '2026-03-02T12:09:59.245Z',
          toolUsed: 'Change-VQA Specialist Model v1.8',
        },
        {
          id: 'step-c4',
          phase: 'Remote-Sensing Inference',
          title: 'Binary Temporal Decision & Mask Activation',
          description: 'Computed cross-temporal difference tokens. Decision logits: YES (0.924), NO (0.051), UNCERTAIN (0.025).',
          status: 'completed',
          latencyMs: 510,
          timestamp: '2026-03-02T12:09:59.290Z',
          toolUsed: 'Change-VQA Specialist Model v1.8',
        },
        {
          id: 'step-c5',
          phase: 'Result Integration',
          title: 'Synthesizing Calibrated Decision',
          description: 'Merged affirmative answer with +3.42 km² quantitative metrics and evidence highlights.',
          status: 'completed',
          latencyMs: 200,
          timestamp: '2026-03-02T12:09:59.800Z',
        },
      ],
    },
    sourceImages: {},
    createdAt: '2026-03-02T12:10:00Z',
  },

  // Scenario 5: Optical + SAR Joint Analysis
  scenario_optical_sar: {
    id: 'res-optsar-05',
    projectId: 'proj-brahmaputra-02',
    query: 'Use both images to identify built-up and water-covered regions.',
    analysisMode: 'OPTICAL_SAR_FUSION',
    modeLabel: 'Cross-Modal Optical-SAR Fusion & Joint Analysis',
    answer: 'By jointly analyzing multi-spectral optical reflectance and cloud-penetrating Sentinel-1 SAR microwave backscatter, all-weather land cover delineation was achieved despite 38.4% optical cloud cover. The active flood channels and inundated backwaters appear with distinct specular microwave absorption (VH backscatter < -22 dB). In contrast, elevated concrete embankments and settlements produce strong double-bounce backscatter (VV > -6 dB), allowing unambiguous distinction between shallow standing water, saturated mudflats, and dry elevated dwellings.',
    evidenceSummary: 'Cross-modal fused probability layer combining optical NDVI/NDWI and SAR VV/VH polarimetric ratio.',
    confidence: {
      score: 0.88,
      tier: 'HIGH',
      explanation: 'High confidence achieved through complementary modality fusion: SAR penetrates cloud cover while Optical resolves spectral ambiguity in non-cloudy clearings.',
      basis: 'Optical-SAR Cross-Modal Fusion Net with sub-pixel spatial alignment (RMSE: 0.18 px).',
    },
    statistics: {
      changedAreaKm2: 28.6,
      percentageChange: 0,
      detectedRegionsCount: 8,
      confidenceMetric: 'Cross-Modal Consensus: 0.88',
      calculationMethod: 'Dual-branch Late Fusion Architecture with Polarimetric Backscatter Calibration',
    },
    evidenceItems: [
      {
        id: 'ev-os-1',
        title: 'SAR Specular Inundation Layer (VV < -22 dB)',
        type: 'optical_sar_overlay',
        description: 'Water boundary delineated underneath cloud cover using radar microwave reflection.',
        layerId: 'layer-sar-water',
        centerCoords: [26.65, 93.18],
        targetZoom: 13,
        activeByDefault: true,
        colorCode: '#22D3EE',
      },
      {
        id: 'ev-os-2',
        title: 'SAR Double-Bounce Elevated Settlements',
        type: 'segmentation_mask',
        description: 'Impervious structures exhibiting high backscatter unaffected by rain or mist.',
        layerId: 'layer-sar-built',
        centerCoords: [26.68, 93.21],
        targetZoom: 14,
        activeByDefault: true,
        colorCode: '#F59E0B',
      },
    ],
    executionTrace: {
      id: 'tr-optsar-05',
      query: 'Use both images to identify built-up and water-covered regions.',
      detectedMode: 'OPTICAL_SAR_FUSION',
      modeLabel: 'Optical-SAR Fusion',
      confidenceScore: 0.88,
      totalDurationMs: 1280,
      specialistModelsUsed: ['Co-Registration Validator', 'Optical-SAR Cross-Modal Fusion Net v3.0', 'SAR Polarimetric Classifier'],
      completedAt: '2026-03-02T13:20:00Z',
      steps: [
        {
          id: 'step-os1',
          phase: 'Input Validation',
          title: 'Dual Modality & CRS Co-Registration Audit',
          description: 'Detected 1 Optical GeoTIFF and 1 SAR GeoTIFF (Sentinel-1 GRD). Extents match in UTM Zone 46N.',
          status: 'completed',
          latencyMs: 110,
          timestamp: '2026-03-02T13:19:58.720Z',
          inputContract: { opticalFormat: 'GeoTIFF', sarFormat: 'SAR GRD', crs: 'EPSG:32646' },
          outputContract: { coRegistrationRmse: 0.18, aligned: true },
        },
        {
          id: 'step-os2',
          phase: 'Query Understanding',
          title: 'Cross-Modal Joint Analysis Intent',
          description: 'Extracted request to leverage both modalities for dual classification: [Water, Built-up].',
          status: 'completed',
          latencyMs: 95,
          timestamp: '2026-03-02T13:19:58.830Z',
        },
        {
          id: 'step-os3',
          phase: 'Specialist Selection',
          title: 'Cross-Modal Model Routing',
          description: 'Controller selected Optical-SAR Cross-Modal Fusion Net v3.0 + SAR Polarimetric Classifier.',
          status: 'completed',
          latencyMs: 55,
          timestamp: '2026-03-02T13:19:58.925Z',
          toolUsed: 'SatQuery Agent Controller',
        },
        {
          id: 'step-os4',
          phase: 'Remote-Sensing Inference',
          title: 'Cross-Attention Feature Fusion',
          description: 'Fused optical spectral bands with SAR VV/VH polarization channels. Segmented water and built-up surfaces.',
          status: 'completed',
          latencyMs: 690,
          timestamp: '2026-03-02T13:19:58.980Z',
          toolUsed: 'Optical-SAR Cross-Modal Fusion Net v3.0',
        },
        {
          id: 'step-os5',
          phase: 'Result Integration',
          title: 'Evidence Layer Synthesis & Narrative Generation',
          description: 'Generated synchronized visual overlays and summarized cloud-penetrating detection results.',
          status: 'completed',
          latencyMs: 330,
          timestamp: '2026-03-02T13:19:59.670Z',
        },
      ],
    },
    sourceImages: {},
    createdAt: '2026-03-02T13:20:00Z',
  },
};

export const SPECIALIST_MODELS: SpecialistModel[] = [
  {
    id: 'model-vqa',
    name: 'RS-VQA Specialist Model',
    task: 'Single-image visual question answering on remote-sensing imagery',
    description: 'Vision-language model fine-tuned on aerial and satellite scenes for answering natural language queries regarding land cover, presence, counts, and spatial relations.',
    version: 'v2.1.4',
    status: 'ready',
    inputType: 'Satellite GeoTIFF / RGB-NIR + Natural Language Question',
    outputType: 'Natural-language answer with calibrated confidence & attention heatmaps',
    backbone: 'EVA-02-CLIP / Swin-B + RoBERTa Fusion Head',
    trainingDatasets: ['RSVQA-LR', 'RSVQA-HR', 'VRSBench (VQA Subset)'],
    latencyP95: '420 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-caption',
    name: 'RS-Captioning Specialist Model',
    task: 'Dense multi-scale geospatial scene description',
    description: 'Generates structured, domain-accurate descriptions of satellite imagery encompassing terrain, vegetation density, water features, infrastructure, and anthropogenic activities.',
    version: 'v2.4.0',
    status: 'ready',
    inputType: 'Single or Multi-spectral Remote-Sensing Image',
    outputType: 'Comprehensive descriptive paragraph & keyword tag breakdown',
    backbone: 'ViT-Large Remote-Sensing Adapted + GPT-style Autoregressive Decoder',
    trainingDatasets: ['VRSBench', 'UCMerced-Captions', 'Sydney-Captions'],
    latencyP95: '380 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-grounding',
    name: 'RS-Grounding Specialist Model',
    task: 'Text-guided spatial localization and bounding box/mask regression',
    description: 'Pinpoints the exact geographic and pixel coordinates of geographical entities, features, or structures described in a natural language prompt.',
    version: 'v2.0.1',
    status: 'ready',
    inputType: 'Remote-Sensing Image + Text Query (e.g. "Highlight the water body")',
    outputType: 'WGS-84 Bounding Box coordinates, Segmentation Mask GeoJSON, Confidence',
    backbone: 'Grounding-DINO adapted with Geospatial Feature Pyramids',
    trainingDatasets: ['VRSBench Grounding', 'DIOR-RSVG'],
    latencyP95: '340 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-change-net',
    name: 'Bi-Temporal Change Detection Net',
    task: 'Pixel-level feature differencing and change mask generation',
    description: 'Siamese dual-branch transformer network trained to identify meaningful surface transformations between two registered satellite observations while ignoring seasonal illumination shifts.',
    version: 'v3.2.0',
    status: 'ready',
    inputType: 'Co-registered T1 & T2 GeoTIFFs (Identical CRS & GSD)',
    outputType: 'Binary Change Mask, Clustered Change Polygons, Area Statistics',
    backbone: 'BIT (Bitemporal Image Transformer) + SegFormer RS Head',
    trainingDatasets: ['LEVIR-CD', 'WHU-CD', 'Siam-S2-Urban'],
    latencyP95: '580 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-change-vqa',
    name: 'Change-VQA Specialist Model',
    task: 'Temporal reasoning and change-focused question answering',
    description: 'Evaluates the nature, extent, and semantic significance of differences between bi-temporal satellite pairs in response to natural-language user questions.',
    version: 'v1.8.2',
    status: 'ready',
    inputType: 'T1 & T2 Imagery + Change Query (e.g. "Has the built-up area increased?")',
    outputType: 'Direct Decision (YES/NO/UNCERTAIN) + Grounded Narrative + Metric Validation',
    backbone: 'Siamese Cross-Attention VLM with Temporal Token Difference Aggregator',
    trainingDatasets: ['CDVQA (Change Detection VQA)', 'LEVIR-VQA'],
    latencyP95: '510 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-optical-sar',
    name: 'Optical-SAR Cross-Modal Fusion Net',
    task: 'Dual-sensor feature alignment, despeckling, and joint classification',
    description: 'Combines optical multispectral imagery with Synthetic Aperture Radar (SAR) microwave backscatter to classify land cover, water boundaries, and built structures across adverse weather conditions.',
    version: 'v3.0.1',
    status: 'ready',
    inputType: 'Optical GeoTIFF (VNIR/SWIR) + SAR GeoTIFF (VV/VH backscatter)',
    outputType: 'Fused Cloud-Free Feature Map, Inundation Extent, High-Backscatter Mask',
    backbone: 'Dual-Stream Dense Cross-Attention Network with Speckle-Aware Filters',
    trainingDatasets: ['SEN12-FLOOD', 'SEN1-2 Cross-Sensor', 'BigEarthNet-MM'],
    latencyP95: '690 ms',
    isDomainAdapted: true,
  },
  {
    id: 'model-validator',
    name: 'Metadata & Co-Registration Validator Tool',
    task: 'Deterministic input verification, CRS reprojection, and refusal guardrails',
    description: 'High-speed deterministic GIS inspection engine. Evaluates raster integrity, verifies EPSG spatial references, calculates bounding overlap, checks radiometric bit depth, and blocks invalid workflows.',
    version: 'v4.1.0',
    status: 'ready',
    inputType: 'Raw Satellite Image File(s) + Metadata Headers',
    outputType: 'Validation Status (READY / WARNING / BLOCKED) + Audit Checkpoints',
    backbone: 'GDAL / Rasterio Core Engine + Geospatial Coordinate Transform Matrix',
    trainingDatasets: ['N/A (Deterministic Geospatial Standard)'],
    latencyP95: '65 ms',
    isDomainAdapted: true,
  },
];

export const BENCHMARK_DATASETS: BenchmarkDataset[] = [
  {
    id: 'bench-rsvqa',
    name: 'RSVQA (Remote Sensing Visual Question Answering)',
    task: 'Single-Image VQA (Presence, Counting, Comparison, Rural/Urban)',
    description: 'Standard academic benchmark containing over 100,000 question-answer pairs paired with Sentinel-2 and high-resolution aerial imagery.',
    metrics: [
      { name: 'Overall Accuracy (HR)', score: '87.4%', baseline: '81.2% (Baseline VLM)' },
      { name: 'Presence Query Accuracy', score: '93.2%', baseline: '88.5%' },
      { name: 'Counting Query Accuracy', score: '78.6%', baseline: '71.0%' },
      { name: 'Comparison Query Accuracy', score: '86.1%', baseline: '80.4%' },
    ],
    evaluationStatus: 'Evaluated',
    source: 'Lobry et al., IEEE TGRS',
  },
  {
    id: 'bench-vrsbench',
    name: 'VRSBench (Vision-Language Remote Sensing Benchmark)',
    task: 'Captioning & Visual Grounding in Satellite Imagery',
    description: 'Rigorous benchmark evaluating high-resolution remote sensing captioning quality (BLEU-4, CIDEr) and text-driven grounding localization (IoU).',
    metrics: [
      { name: 'Grounding mIoU (Mean IoU)', score: '62.8%', baseline: '54.2%' },
      { name: 'Grounding Acc@0.5', score: '74.1%', baseline: '65.9%' },
      { name: 'Captioning CIDEr Score', score: '1.24', baseline: '1.08' },
      { name: 'Captioning BLEU-4', score: '38.5%', baseline: '33.1%' },
    ],
    evaluationStatus: 'Evaluated',
    source: 'IEEE Geoscience & Remote Sensing Society',
  },
  {
    id: 'bench-cdvqa',
    name: 'CDVQA (Change Detection Visual Question Answering)',
    task: 'Bi-Temporal Change Understanding & Temporal VQA',
    description: 'Bi-temporal satellite dataset designed specifically to assess whether vision-language models can correctly answer complex questions regarding changes over time.',
    metrics: [
      { name: 'Change Verification Accuracy', score: '91.8%', baseline: '83.4%' },
      { name: 'Change Type Classification', score: '84.6%', baseline: '76.2%' },
      { name: 'Spatial Change Grounding F1', score: '82.9%', baseline: '74.1%' },
    ],
    evaluationStatus: 'Evaluated',
    source: 'International Journal of Remote Sensing',
  },
  {
    id: 'bench-bigearthnet',
    name: 'BigEarthNet-MM (Multimodal Optical + SAR)',
    task: 'Cross-Modal Optical-SAR Representation Learning',
    description: 'Large-scale multimodal remote-sensing dataset of 590,326 Sentinel-1 & Sentinel-2 image pairs covering diverse European bio-geographical regions.',
    metrics: [
      { name: 'Multimodal Mean F1', score: '89.2%', baseline: '82.7%' },
      { name: 'Cloud-Resilient Classification F1', score: '86.4%', baseline: '71.5%' },
    ],
    evaluationStatus: 'Evaluated',
    source: 'TU Berlin & European Space Agency (ESA)',
  },
  {
    id: 'bench-isro-sac',
    name: 'ISRO / Space Applications Centre (SAC) Domain Suite',
    task: 'Indian Subcontinent Agro-Climatic & Urban GeoAI Evaluation',
    description: 'Specialized domain evaluation framework calibrated for Indian remote sensing sensors (Resourcesat LISS-IV, Cartosat, and RISAT SAR).',
    metrics: [
      { name: 'LISS-IV Agro-Classification', score: 'Evaluation Pending', baseline: 'Awaiting SAC Run' },
      { name: 'RISAT-1A SAR Inundation F1', score: 'Evaluation Pending', baseline: 'Awaiting SAC Run' },
      { name: 'Peri-Urban Growth Delineation', score: 'Evaluation Pending', baseline: 'Awaiting SAC Run' },
    ],
    evaluationStatus: 'Evaluation Pending',
    source: 'SIH 2026 Problem Statement SIH26167 / ISRO Evaluation Track',
  },
];

export const DEMO_REPORTS: ReportItem[] = [
  {
    id: 'rep-urban-01',
    reportNumber: 'SQ-2026-URB-001',
    projectId: 'proj-urban-01',
    projectName: 'Bengaluru Peri-Urban Expansion',
    title: 'Autonomous Bi-Temporal Infrastructure Expansion & Change Detection Report',
    query: 'What changed between these two dates?',
    analysisMode: 'Bi-Temporal Change Analysis',
    generatedDate: '2026-03-02 12:05:10 IST',
    analyst: 'SatQuery AI Agent Controller (Auto-Certified)',
    organization: 'ISRO / SIH 2026 Geospatial Division',
    status: 'Final',
    resultId: 'res-bitemp-03',
  },
  {
    id: 'rep-flood-02',
    reportNumber: 'SQ-2026-FLD-002',
    projectId: 'proj-brahmaputra-02',
    projectName: 'Brahmaputra Basin Flood Inundation',
    title: 'Multimodal Optical-SAR Cloud-Penetrating Inundation Assessment Report',
    query: 'Use both images to identify built-up and water-covered regions.',
    analysisMode: 'Optical + SAR Fusion',
    generatedDate: '2026-03-02 13:21:00 IST',
    analyst: 'SatQuery AI Agent Controller (Auto-Certified)',
    organization: 'ISRO / SIH 2026 Geospatial Division',
    status: 'Final',
    resultId: 'res-optsar-05',
  },
  {
    id: 'rep-agri-03',
    reportNumber: 'SQ-2026-AGR-003',
    projectId: 'proj-punjab-agri-03',
    projectName: 'Punjab Crop Phenology & Water Bodies',
    title: 'High-Resolution Irrigation Water Body Localization & Grounding Report',
    query: 'Highlight the water body.',
    analysisMode: 'Region Grounding',
    generatedDate: '2026-03-02 11:16:00 IST',
    analyst: 'SatQuery AI Agent Controller (Auto-Certified)',
    organization: 'ISRO / SIH 2026 Geospatial Division',
    status: 'Final',
    resultId: 'res-grounding-02',
  },
];
